import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,access} from 'node:fs/promises';

const root=new URL('../',import.meta.url);
const read=path=>readFile(new URL(path,root),'utf8');

test('версия интерфейса, ресурсов и автономного кеша согласована',async()=>{
  const [index,app,ui,store,worker,css]=await Promise.all(['index.html','src/app.js','src/ui.js','src/store.js','sw.js','styles/app.css'].map(read));
  assert.match(index,/manifest\.webmanifest\?v=46.1/);
  assert.match(index,/styles\/app\.css\?v=46.1/);
  assert.match(index,/src\/app\.js\?v=46.1/);
  assert.match(app,/sw\.js\?v=46.1/);
  assert.doesNotMatch(app,/data-planet-pulse/);
  assert.match(ui,/APP_VERSION='46.1'/);
  assert.match(ui,/class="planet-art"/);
  assert.doesNotMatch(ui,/data-planet-pulse/);
  assert.match(ui,/assets\/planets\/\$\{code\.toLowerCase\(\)\}\.webp\?v=46.1/);
  assert.match(ui,/class="world-map"/);
  assert.match(ui,/moonvit-satellite/);
  assert.match(ui,/planetProgress/);
  assert.match(ui,/trainProgramCard/);
  assert.match(ui,/trainProgramModal/);
  assert.match(ui,/Следующий день — завтра/);
  assert.match(app,/data-save-train-program/);
  assert.match(store,/normalizeTrainProgram/);
  assert.match(index,/>Прогресс<\/small>/);
  assert.match(ui,/class="progress-world/);
  assert.match(ui,/Общее развитие/);
  assert.match(ui,/Без поспешных выводов/);
  assert.match(ui,/actionInsight\.ready\?/);
  assert.match(ui,/relationInsight\.ready\?relationship\(\):null/);
  assert.match(ui,/Вечерняя отметка сравнивается с состоянием следующего утра/);
  assert.match(ui,/--surface-detail/);
  assert.match(ui,/--atmosphere-strength/);
  assert.match(css,/\.world-node\.planet-focus/);
  assert.match(css,/\.world-node\.planet-train/);
  assert.match(css,/\.world-node\.planet-balance/);
  assert.match(css,/\.world-node\.planet-grow/);
  assert.match(css,/\.world-node\.planet-capital/);
  assert.match(css,/\.toast\{pointer-events:none\}/);
  assert.match(css,/\.modal-wrap\{z-index:50\}/);
  assert.match(css,/@keyframes inner-core/);
  assert.match(css,/@keyframes aura-breathe/);
  assert.match(css,/prefers-reduced-motion:reduce/);
  assert.match(store,/data\.js\?v=46.1/);
  assert.match(store,/planetProgress/);
  assert.match(worker,/stack-moonvit-shell-v46.1/);
  assert.match(worker,/assets\/planets\/capital\.webp\?v=46.1/);
  const shell=[...worker.matchAll(/'\.\/([^']+)'/g)].map(match=>match[1].split('?')[0]).filter(Boolean);
  await Promise.all(shell.map(path=>access(new URL(path,root))));
  const manifest=await read('manifest.webmanifest');
  assert.doesNotThrow(()=>JSON.parse(manifest));
});
