(() => {
  const KEY='stack-moonvit-v2',OLD='stack-moonvit-v1',today=new Date().toISOString().slice(0,10);
  const prior=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD)||'{}');
  const records=prior.records||{};
  if(!records[today]) records[today]={done:prior.done||[],sleep:null,energy:null};
  const state={view:'today',onboarded:Boolean(prior.onboarded),step:0,records};
  const actions=[['moon','Принять Moonvit Moon','Вечер · SLEEP STACK','Moonvit'],['sleep','Оценить сон и энергию','2 коротких вопроса',''],['screen','Без экрана перед сном','30 минут · дисциплина',''],['bed','Лечь до выбранного времени','До 00:00 · SLEEP STACK','']];
  const rec=()=>state.records[today];
  const save=()=>localStorage.setItem(KEY,JSON.stringify({onboarded:state.onboarded,records:state.records}));
  const fmt=d=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'));
  const dayTitle=new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
  const header=(title,sub)=>`<header class="topbar"><div class="brand">STACK <span class="moon-mark">× MOONVIT</span></div><div class="avatar">А</div></header><p class="eyebrow">${dayTitle}</p><h1>${title}</h1><p class="subtitle">${sub}</p>`;
  const task=([id,title,meta,tag])=>`<button class="task ${rec().done.includes(id)?'done':''}" data-task="${id}"><span class="check">${rec().done.includes(id)?'✓':''}</span><span class="task-copy"><span class="task-title">${title}</span><span class="task-meta">${id==='sleep'&&rec().sleep?`Сон ${rec().sleep}/5 · энергия ${rec().energy}/5`:meta}</span></span>${tag?`<span class="tag">${tag}</span>`:''}</button>`;
  const lastDays=()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-i);return d.toISOString().slice(0,10)});
  const discipline=()=>{const ds=lastDays().filter(d=>state.records[d]);if(!ds.length)return 0;return Math.round(ds.reduce((s,d)=>s+(state.records[d].done?.length||0)/actions.length,0)/ds.length*100)};
  const history=()=>lastDays().map(d=>{const r=state.records[d];return `<button class="history-row" data-date="${d}"><span><b>${d===today?'Сегодня':fmt(d)}</b><small>${r?`${r.done?.length||0} из ${actions.length} действий`:'Нет данных'}</small></span><span class="history-score">${r?.sleep?`Сон ${r.sleep} · энергия ${r.energy}`:'—'} ›</span></button>`}).join('');
  const insight=()=>{const rows=Object.values(state.records).filter(r=>r.sleep&&r.energy);if(rows.length<3)return `Нужно ещё ${3-rows.length} ежедневных отметки, чтобы STACK сформировал первое личное наблюдение.`;const avg=(rows.reduce((s,r)=>s+r.sleep,0)/rows.length).toFixed(1);return `За ${rows.length} отмеченных дня средняя субъективная оценка сна — ${avg} из 5. Продолжай наблюдение: данных пока недостаточно для вывода о причинах.`};
  const views={
    today:()=>`${header('Доброе утро, Алексей','Дисциплина начинается с нескольких ясных действий.')}<section class="card progress-card"><div class="progress-top"><div><h3>Эксперимент со сном</h3><p>Наблюдаем без поспешных выводов</p></div><span class="day">День ${Math.min(30,Object.keys(state.records).length)} из 30</span></div><div class="progress"><i style="width:${Math.min(100,Object.keys(state.records).length/30*100)}%"></i></div><div class="moon-row"><i class="planet"></i><span>Moon · Sleep & Relaxation</span></div></section><div class="section-head"><h2>Сегодня</h2><button id="reset">Сбросить</button></div><div class="tasks">${actions.map(task).join('')}</div><div class="section-head"><h2>STACK заметил</h2><button data-view="insights">История</button></div><section class="card insight"><p>${insight()}</p><span class="confidence">Наблюдение, а не медицинский вывод</span></section>`,
    stacks:()=>`${header('Твои стеки','Системы действий, которые помогают улучшать себя.')}<div class="section-head"><h2>Активные</h2></div><div class="stack-grid"><section class="card stack-card dark"><div><span class="stack-icon">◐</span><p class="eyebrow stack-label">SLEEP STACK</p><h2>Сон и восстановление</h2></div><span class="metric">${actions.length} действия · Moonvit подключён</span></section><section class="card stack-card"><div><span class="stack-icon">↗</span><p class="eyebrow stack-label">FOCUS STACK</p><h2>Фокус и энергия</h2></div><span class="metric">Следующий этап развития</span></section><button class="card stack-card add-card" id="addStack">＋ Создать новый стек</button></div>`,
    insights:()=>`${header('Прогресс','Данные без перегруженных графиков.')}<section class="card discipline-card"><p class="eyebrow">Дисциплина за 7 дней</p><div class="discipline-value"><b>${discipline()}%</b><span>выполненного плана</span></div><div class="discipline-line"><i style="width:${discipline()}%"></i></div></section><div class="section-head"><h2>История</h2><span class="confidence">Последние 7 дней</span></div><div class="history">${history()}</div><div class="section-head"><h2>Первое наблюдение</h2></div><section class="card insight"><p>${insight()}</p><span class="confidence">Причинно-следственная связь не установлена</span></section>`,
    profile:()=>`${header('Профиль','Настройки твоей системы и подключений.')}<section class="card profile-card"><p class="eyebrow">Твоя цель</p><h2>Улучшить сон</h2><p class="subtitle profile-note">SLEEP STACK · Moonvit Moon</p></section><div class="settings"><div class="setting"><span>Moonvit</span><span>Подключён ›</span></div><div class="setting"><span>Дней с данными</span><span>${Object.keys(state.records).length} ›</span></div><button class="setting setting-button" id="restart"><span>Пройти настройку заново</span><span>›</span></button></div>`
  };
  function render(view=state.view){state.view=view;document.querySelector('#app').innerHTML=views[view]();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo(0,0)}
  function onboarding(){const steps=[`<p class="eyebrow">Шаг 1 из 3</p><h1>Что ты хочешь улучшить?</h1><p class="subtitle">Начнём с одной цели. Остальное можно добавить позже.</p><div class="choices"><button class="choice selected">Сон и восстановление<small>Режим, качество сна, энергия</small></button><button class="choice">Фокус и продуктивность<small>Концентрация и глубокая работа</small></button></div><button class="primary" data-next>Продолжить</button>`,`<p class="eyebrow">Шаг 2 из 3</p><h1>Подключить Moonvit?</h1><p class="subtitle">Moon станет одной из переменных внутри твоего SLEEP STACK.</p><div class="product-choice"><i class="planet"></i><div><b>Moon</b><small>Sleep & Relaxation</small></div><span>Выбрано ✓</span></div><button class="primary" data-next>Подключить</button><button class="secondary" data-next>Пока без Moonvit</button>`,`<p class="eyebrow">Шаг 3 из 3</p><h1>Твой SLEEP STACK готов</h1><p class="subtitle">Действия → дисциплина → состояние → наблюдения → улучшение.</p><div class="stack-list"><span>Лечь вовремя</span><span>Без экрана перед сном</span><span>Moonvit Moon</span><span>Оценить сон утром</span></div><button class="primary" id="finish">Начать</button>`];document.querySelector('#app').innerHTML=`<div class="onboarding"><div class="dots"><i></i><i></i><i></i></div>${steps[state.step]}</div>`;document.querySelectorAll('.dots i')[state.step].classList.add('active');document.querySelector('.bottom-nav').classList.add('hidden')}
  function checkin(){document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap"><div class="modal"><button class="close">×</button><p class="eyebrow">Утренняя отметка</p><h2>Как ты себя чувствуешь?</h2><label>Качество сна <output id="sleepOut">${rec().sleep||3}</output></label><input id="sleepRange" type="range" min="1" max="5" value="${rec().sleep||3}"><label>Энергия <output id="energyOut">${rec().energy||3}</output></label><input id="energyRange" type="range" min="1" max="5" value="${rec().energy||3}"><button class="primary" id="saveCheckin">Сохранить</button></div></div>`)}
  function detail(date){const r=state.records[date];document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap"><div class="modal"><button class="close">×</button><p class="eyebrow">${fmt(date)}</p><h2>${r?'Данные дня':'Пока нет данных'}</h2>${r?`<div class="day-detail">${actions.map(([id,t])=>`<span>${r.done?.includes(id)?'✓':'○'} ${t}</span>`).join('')}</div><p class="subtitle">Сон: ${r.sleep||'—'} из 5 · энергия: ${r.energy||'—'} из 5</p>`:'<p class="subtitle">В этот день отметки не сохранялись.</p>'}</div></div>`)}
  function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
  document.addEventListener('input',e=>{if(e.target.id==='sleepRange')document.querySelector('#sleepOut').value=e.target.value;if(e.target.id==='energyRange')document.querySelector('#energyOut').value=e.target.value});
  document.addEventListener('click',e=>{if(e.target.closest('[data-next]')){state.step=Math.min(2,state.step+1);onboarding();return}if(e.target.id==='finish'){state.onboarded=true;save();document.querySelector('.bottom-nav').classList.remove('hidden');render();return}const nav=e.target.closest('[data-view]');if(nav){render(nav.dataset.view);return}const row=e.target.closest('[data-date]');if(row){detail(row.dataset.date);return}const el=e.target.closest('[data-task]');if(el){const id=el.dataset.task;if(id==='sleep'){checkin();return}rec().done=rec().done.includes(id)?rec().done.filter(x=>x!==id):[...rec().done,id];save();render();toast(rec().done.includes(id)?'Выполнено':'Отметка снята');return}if(e.target.classList.contains('close')){e.target.closest('.modal-wrap').remove();return}if(e.target.id==='saveCheckin'){rec().sleep=+document.querySelector('#sleepRange').value;rec().energy=+document.querySelector('#energyRange').value;if(!rec().done.includes('sleep'))rec().done.push('sleep');save();e.target.closest('.modal-wrap').remove();render();toast('Состояние сохранено');return}if(e.target.id==='reset'){rec().done=[];rec().sleep=null;rec().energy=null;save();render();toast('Сегодняшние отметки сброшены')}if(e.target.id==='restart'){state.onboarded=false;state.step=0;save();onboarding()}if(e.target.id==='addStack')toast('Новые стеки появятся дальше')});
  state.onboarded?render():onboarding();
})();
