const saved=JSON.parse(localStorage.getItem('stack-moonvit-v1')||'{}');
const state={done:new Set(saved.done||[]),view:'today',checkins:saved.checkins||[],onboarded:Boolean(saved.onboarded),step:0};
const persist=()=>localStorage.setItem('stack-moonvit-v1',JSON.stringify({done:[...state.done],checkins:state.checkins,onboarded:state.onboarded}));
const renderHeader=(title,sub)=>`<header class="topbar"><div><div class="brand">STACK <span class="moon-mark">× MOONVIT</span></div></div><div class="avatar">А</div></header><p class="eyebrow">${new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</p><h1>${title}</h1><p class="subtitle">${sub}</p>`;
const views={
today:()=>`${renderHeader('Доброе утро, Алексей','Твой день — спокойно и по существу.')}<section class="card progress-card"><div class="progress-top"><div><h3>Эксперимент со сном</h3><p>Наблюдаем без поспешных выводов</p></div><span class="day">День 12 из 30</span></div><div class="progress"><i></i></div><div class="moon-row"><i class="planet"></i><span>Moon · Sleep & Relaxation</span></div></section><div class="section-head"><h2>Сегодня</h2><button id="reset">Сбросить</button></div><div class="tasks">${[['moon','Принять Moonvit Moon','Вечер · SLEEP STACK'],['sleep','Отметить качество сна','1 короткий вопрос'],['focus','Фокус-сессия','45 минут · FOCUS STACK']].map(([id,t,m],i)=>`<div class="task ${state.done.has(id)?'done':''}" data-task="${id}"><span class="check">${state.done.has(id)?'✓':''}</span><div class="task-copy"><div class="task-title">${t}</div><div class="task-meta">${m}</div></div>${i===0?'<span class="tag">Moonvit</span>':''}</div>`).join('')}</div><div class="section-head"><h2>STACK заметил</h2><button data-view="insights">Все</button></div><section class="card insight"><p>В дни, когда ты ложишься до 00:00, утренняя энергия обычно выше.</p><span class="confidence">Наблюдение по 9 дням · это не медицинский вывод</span></section>`,
stacks:()=>`${renderHeader('Твои стеки','Не отдельные привычки, а связанные системы.')}<div class="section-head"><h2>Активные</h2><button>Изменить</button></div><div class="stack-grid"><section class="card stack-card dark"><div><span class="stack-icon">◐</span><p class="eyebrow" style="color:#c3c8dc;margin-top:18px">SLEEP STACK</p><h2>Сон и восстановление</h2></div><span class="metric">Moonvit подключён · 12 дней данных</span></section><section class="card stack-card"><div><span class="stack-icon">↗</span><p class="eyebrow" style="margin-top:18px">FOCUS STACK</p><h2>Фокус и энергия</h2></div><span class="metric">7 сессий на этой неделе</span></section><button class="card stack-card add-card" id="addStack">＋ Создать новый стек</button></div>`,
insights:()=>`${renderHeader('Инсайты','Закономерности появляются только когда данных достаточно.')}<section class="card" style="margin-top:24px"><p class="eyebrow">Состояние за 7 дней</p><div class="hero-stat"><b>4.1</b><span>из 5 · выше на 0.3</span></div><div class="trend">${[45,60,52,66,72,80,70].map(x=>`<i style="height:${x}%"></i>`).join('')}</div></section><div class="section-head"><h2>Наблюдения</h2></div><section class="card insight"><p>Лучшие фокус-сессии чаще проходят до 11:00 после сна дольше 7 часов.</p><span class="confidence">Повторилось в 6 из 8 подходящих дней</span></section><section class="card" style="margin-top:10px"><p class="eyebrow">Эксперимент Moonvit</p><p class="subtitle">Промежуточные данные ещё не показывают результат. Итог появится после 30-го дня с учётом сна и режима.</p></section>`,
profile:()=>`${renderHeader('Профиль','Настройки твоей системы и подключений.')}<section class="card" style="margin-top:24px"><p class="eyebrow">Твой план</p><h2>Базовый</h2><p class="subtitle" style="margin-top:8px">2 активных стека · простые инсайты</p><button class="primary" id="upgrade">Посмотреть Plus</button></section><div class="settings"><div class="setting"><span>Moonvit</span><span>1 продукт подключён ›</span></div><div class="setting"><span>Напоминания</span><span>2 активных ›</span></div><div class="setting"><span>Приватность данных</span><span>Настроить ›</span></div><div class="setting"><span>О приложении</span><span>STACK 0.1 ›</span></div></div>`};
function render(view=state.view){state.view=view;document.querySelector('#app').innerHTML=views[view]();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo(0,0)}
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function onboarding(){const steps=[`<p class="eyebrow">Шаг 1 из 3</p><h1>Что ты хочешь улучшить?</h1><p class="subtitle">Начнём с одной цели. Остальное можно добавить позже.</p><div class="choices"><button class="choice selected">Сон и восстановление<small>Режим, качество сна, энергия</small></button><button class="choice">Фокус и продуктивность<small>Концентрация и глубокая работа</small></button></div><button class="primary" data-next>Продолжить</button>`,`<p class="eyebrow">Шаг 2 из 3</p><h1>Подключить Moonvit?</h1><p class="subtitle">Moon станет одной из переменных твоего SLEEP STACK, а не центром приложения.</p><div class="product-choice"><i class="planet"></i><div><b>Moon</b><small>Sleep & Relaxation</small></div><span>Выбрано ✓</span></div><button class="primary" data-next>Подключить</button><button class="secondary" data-next>Пока без Moonvit</button>`,`<p class="eyebrow">Шаг 3 из 3</p><h1>Твой SLEEP STACK готов</h1><p class="subtitle">Действия → дисциплина → состояние → наблюдения → улучшение.</p><div class="stack-list"><span>Лечь вовремя</span><span>Без экрана перед сном</span><span>Moonvit Moon</span><span>Оценить сон утром</span></div><button class="primary" id="finish">Начать</button>`];document.querySelector('#app').innerHTML=`<div class="onboarding"><div class="dots"><i></i><i></i><i></i></div>${steps[state.step]}</div>`;document.querySelectorAll('.dots i')[state.step].classList.add('active');document.querySelector('.bottom-nav').classList.add('hidden')}
function checkin(){document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap"><div class="modal"><button class="close">×</button><p class="eyebrow">Утренняя отметка</p><h2>Как ты себя чувствуешь?</h2><label>Качество сна <output id="sleepOut">3</output></label><input id="sleepRange" type="range" min="1" max="5" value="3"><label>Энергия <output id="energyOut">3</output></label><input id="energyRange" type="range" min="1" max="5" value="3"><button class="primary" id="saveCheckin">Сохранить</button></div></div>`)}
document.addEventListener('input',e=>{if(e.target.id==='sleepRange')document.querySelector('#sleepOut').value=e.target.value;if(e.target.id==='energyRange')document.querySelector('#energyOut').value=e.target.value});
document.addEventListener('click',e=>{if(e.target.closest('[data-next]')){state.step=Math.min(2,state.step+1);onboarding();return}if(e.target.classList.contains('choice')){document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));e.target.classList.add('selected');return}if(e.target.id==='finish'){state.onboarded=true;persist();document.querySelector('.bottom-nav').classList.remove('hidden');render();return}const nav=e.target.closest('[data-view]');if(nav){render(nav.dataset.view);return}const task=e.target.closest('[data-task]');if(task){const id=task.dataset.task;if(id==='sleep'){checkin();return}state.done.has(id)?state.done.delete(id):state.done.add(id);persist();render();toast(state.done.has(id)?'Выполнено':'Отметка снята');return}if(e.target.classList.contains('close')){e.target.closest('.modal-wrap').remove();return}if(e.target.id==='saveCheckin'){state.checkins.push({date:new Date().toISOString(),sleep:+document.querySelector('#sleepRange').value,energy:+document.querySelector('#energyRange').value});state.done.add('sleep');persist();document.querySelector('.modal-wrap').remove();render();toast('Состояние сохранено');return}if(e.target.id==='reset'){state.done.clear();persist();render();toast('День сброшен')}if(e.target.id==='addStack')toast('Конструктор появится на следующем этапе');if(e.target.id==='upgrade')toast('Plus появится после первых инсайтов')});
state.onboarded?render():onboarding();
