const state={done:new Set(),view:'today'};
const top=(title,sub)=>`<header class="topbar"><div><div class="brand">STACK <span class="moon-mark">× MOONVIT</span></div></div><div class="avatar">А</div></header><p class="eyebrow">Вторник, 15 сентября</p><h1>${title}</h1><p class="subtitle">${sub}</p>`;
const views={
today:()=>`${top('Доброе утро, Алексей','Твой день — спокойно и по существу.')}<section class="card progress-card"><div class="progress-top"><div><h3>Эксперимент со сном</h3><p>Наблюдаем без поспешных выводов</p></div><span class="day">День 12 из 30</span></div><div class="progress"><i></i></div><div class="moon-row"><i class="planet"></i><span>Moon · Sleep & Relaxation</span></div></section><div class="section-head"><h2>Сегодня</h2><button id="reset">Сбросить</button></div><div class="tasks">${[['moon','Принять Moonvit Moon','Вечер · SLEEP STACK'],['sleep','Отметить качество сна','1 короткий вопрос'],['focus','Фокус-сессия','45 минут · FOCUS STACK']].map(([id,t,m],i)=>`<div class="task ${state.done.has(id)?'done':''}" data-task="${id}"><span class="check">${state.done.has(id)?'✓':''}</span><div class="task-copy"><div class="task-title">${t}</div><div class="task-meta">${m}</div></div>${i===0?'<span class="tag">Moonvit</span>':''}</div>`).join('')}</div><div class="section-head"><h2>STACK заметил</h2><button data-view="insights">Все</button></div><section class="card insight"><p>В дни, когда ты ложишься до 00:00, утренняя энергия обычно выше.</p><span class="confidence">Наблюдение по 9 дням · это не медицинский вывод</span></section>`,
stacks:()=>`${top('Твои стеки','Не отдельные привычки, а связанные системы.')}<div class="section-head"><h2>Активные</h2><button>Изменить</button></div><div class="stack-grid"><section class="card stack-card dark"><div><span class="stack-icon">◐</span><p class="eyebrow" style="color:#c3c8dc;margin-top:18px">SLEEP STACK</p><h2>Сон и восстановление</h2></div><span class="metric">Moonvit подключён · 12 дней данных</span></section><section class="card stack-card"><div><span class="stack-icon">↗</span><p class="eyebrow" style="margin-top:18px">FOCUS STACK</p><h2>Фокус и энергия</h2></div><span class="metric">7 сессий на этой неделе</span></section><button class="card stack-card add-card" id="addStack">＋ Создать новый стек</button></div>`,
insights:()=>`${top('Инсайты','Закономерности появляются только когда данных достаточно.')}<section class="card" style="margin-top:24px"><p class="eyebrow">Состояние за 7 дней</p><div class="hero-stat"><b>4.1</b><span>из 5 · выше на 0.3</span></div><div class="trend">${[45,60,52,66,72,80,70].map(x=>`<i style="height:${x}%"></i>`).join('')}</div></section><div class="section-head"><h2>Наблюдения</h2></div><section class="card insight"><p>Лучшие фокус-сессии чаще проходят до 11:00 после сна дольше 7 часов.</p><span class="confidence">Повторилось в 6 из 8 подходящих дней</span></section><section class="card" style="margin-top:10px"><p class="eyebrow">Эксперимент Moonvit</p><p class="subtitle">Промежуточные данные ещё не показывают результат. Итог появится после 30-го дня с учётом сна и режима.</p></section>`,
profile:()=>`${top('Профиль','Настройки твоей системы и подключений.')}<section class="card" style="margin-top:24px"><p class="eyebrow">Твой план</p><h2>Базовый</h2><p class="subtitle" style="margin-top:8px">2 активных стека · простые инсайты</p><button class="primary" id="upgrade">Посмотреть Plus</button></section><div class="settings"><div class="setting"><span>Moonvit</span><span>1 продукт подключён ›</span></div><div class="setting"><span>Напоминания</span><span>2 активных ›</span></div><div class="setting"><span>Приватность данных</span><span>Настроить ›</span></div><div class="setting"><span>О приложении</span><span>STACK 0.1 ›</span></div></div>`};
function render(view=state.view){state.view=view;document.querySelector('#app').innerHTML=views[view]();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo(0,0)}
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){render(nav.dataset.view);return}const task=e.target.closest('[data-task]');if(task){const id=task.dataset.task;state.done.has(id)?state.done.delete(id):state.done.add(id);render();toast(state.done.has(id)?'Отмечено':'Отметка снята');return}if(e.target.id==='reset'){state.done.clear();render();toast('День сброшен')}if(e.target.id==='addStack')toast('Конструктор стека откроется здесь') ;if(e.target.id==='upgrade')toast('Plus появится после первых инсайтов')});
render();
