import {STACK_LIBRARY,TODAY,formatDay,longToday} from './data.js';
import {store} from './store.js';

const header=(title,subtitle)=>`<header class="topbar"><div class="brand">STACK <span>× MOONVIT</span></div><div class="avatar">А</div></header><p class="eyebrow">${longToday()}</p><h1>${title}</h1><p class="subtitle">${subtitle}</p>`;
const metricText=(code,values)=>{if(!values)return null;const labels=Object.fromEntries(STACK_LIBRARY[code].checkin.questions.map(q=>[q.key,q.label.toLowerCase()]));return Object.entries(values).map(([key,value])=>`${labels[key]} ${value}/5`).join(' · ')};
const task=(action,code)=>{const record=store.record(),done=record.done.includes(action.id),checkin=action.checkin?metricText(code,store.checkin(code)):null;return `<button class="task ${done?'done':''}" data-task="${action.id}"><i>${done?'✓':''}</i><span><b>${action.title}</b><small>${checkin||action.meta}</small></span>${action.product?'<em>Moonvit</em>':''}</button>`};
const observation=(code=store.state.activeStack)=>{const stack=STACK_LIBRARY[code],rows=Object.values(store.state.records).map(r=>r.checkins?.[code]).filter(Boolean);if(rows.length<3)return `Ещё ${3-rows.length} ${rows.length===2?'отметка':'отметки'} — и STACK начнёт показывать динамику ${stack.title.toLowerCase()}.`;const keys=stack.checkin.questions.map(q=>q.key),averages=keys.map(key=>(rows.reduce((sum,row)=>sum+(Number(row[key])||0),0)/rows.length).toFixed(1));return `За ${rows.length} отмеченных дней: ${stack.checkin.questions.map((q,i)=>`${q.label.toLowerCase()} — ${averages[i]} из 5`).join(', ')}. Продолжай наблюдение, чтобы увидеть устойчивую закономерность.`};
const relationship=()=>{const result=store.relationships();if(result.reason==='single')return {title:'Нужно второе направление',text:'Добавь ещё один стек и отмечай состояние в обоих направлениях — тогда здесь появится сравнение.',progress:0};const names=code=>STACK_LIBRARY[code].title.toLowerCase();if(!result.ready){const unit=result.needed===1?'день':result.needed<5?'дня':'дней';return {title:`${result.overlap} из 5 совместных дней`,text:`Ещё ${result.needed} ${unit} с отметками «${names(result.left)}» и «${names(result.right)}», чтобы проверить возможную связь.`,progress:result.overlap/5*100}}const strength=Math.abs(result.correlation),direction=result.correlation>=0?'меняются в одном направлении':'часто меняются в противоположных направлениях';return {title:`${STACK_LIBRARY[result.left].code} ↔ ${STACK_LIBRARY[result.right].code}`,text:strength<.35?`За ${result.overlap} совместных дней устойчивой связи пока не видно. Это тоже полезное наблюдение.`:`За ${result.overlap} совместных дней показатели ${direction}. Продолжай отмечать данные — ранняя закономерность ещё может измениться.`,progress:Math.min(100,result.overlap/14*100)}};
const improvement=()=>{const running=store.experiment();if(running)return `<section class="card discipline experiment"><p class="eyebrow">Эксперимент · ${running.elapsed} из 3 дней</p><h2>${running.action.title}</h2><p class="subtitle">Не меняй весь стек. Три дня подряд наблюдай только за этим действием.</p><div><b>${running.done}/${running.elapsed}</b><span>выполнено в доступные дни</span></div><i><span style="width:${running.elapsed?running.done/running.elapsed*100:0}%"></span></i>${running.complete?'<button class="primary" data-finish-experiment>Завершить эксперимент</button>':'<small>Отмечай действие на экране «Сегодня»</small>'}</section>`;const action=store.weakestAction();return `<section class="card experiment"><p class="eyebrow">Следующее улучшение</p><h2>${action?.title||'Продолжай наблюдение'}</h2><p class="subtitle">${action?`Это действие отмечалось реже других. Проверь его три дня подряд, не добавляя новых задач.`:'Сначала сделай несколько ежедневных отметок.'}</p>${action?'<button class="primary" data-start-experiment>Начать эксперимент на 3 дня</button>':''}</section>`};

export function todayView(){const stack=store.stack(),actions=store.actions(),done=store.completed(),switcher=store.state.installed.length>1?`<div class="quick-stacks" aria-label="Переключить активный стек">${store.state.installed.map(code=>`<button class="${code===stack.code?'active':''}" data-quick-stack="${code}"><span>${STACK_LIBRARY[code].icon}</span>${code}<small>${store.completed(code)}/${store.actions(code).length}</small></button>`).join('')}</div>`:'';return `${header('Доброе утро, Александр','Сегодня — только действия активного стека.')}${switcher}<section class="hero"><div><h3>${stack.title}</h3><p>${stack.purpose}</p></div><span>${stack.code} STACK</span><div class="progress"><i style="width:${actions.length?done/actions.length*100:0}%"></i></div><div class="hero-foot"><small>${done} из ${actions.length} выполнено</small>${stack.code==='SLEEP'&&store.state.moonConnected?'<div class="product"><i></i> Moon · Sleep & Relaxation</div>':''}</div></section><div class="section"><h2>Сегодня</h2>${done?'<button data-reset>Сбросить ${stack.code}</button>':''}</div><div class="tasks">${actions.map(a=>task(a,stack.code)).join('')}</div><div class="section"><h2>STACK заметил</h2><button data-view="insights">История</button></div><section class="card insight"><p>${observation()}</p><small>Наблюдение, а не медицинский вывод</small></section>`}

export function stacksView(){return `${header('Твои стеки','Один активный стек определяет ясный план на сегодня.')}<div class="section"><h2>Мои системы</h2><small>${store.state.installed.length} всего</small></div><div class="stack-grid">${store.state.installed.map(code=>{const s=STACK_LIBRARY[code];return `<section class="stack-card ${store.state.activeStack===code?'active':''}" data-activate="${code}">${s.removable?`<button class="remove" data-remove="${code}" aria-label="Удалить ${code} STACK">×</button>`:''}<strong>${s.icon}</strong><small>${s.code} STACK ${store.state.activeStack===code?'· АКТИВЕН':''}</small><h2>${s.title}</h2><p>${s.purpose}</p></section>`}).join('')}<button class="add-stack" data-builder>＋ Добавить направление</button></div>`}

export function insightsView(){const code=store.state.activeStack,stack=store.stack(),actions=store.actions(),days=store.lastDays(),discipline=store.discipline(),link=relationship();return `${header('Прогресс',`${stack.code} STACK · наблюдаем действия и состояние.`)}<section class="card discipline"><p class="eyebrow">Дисциплина за 7 дней</p><div><b>${discipline}%</b><span>выполненного плана</span></div><i><span style="width:${discipline}%"></span></i></section><div class="section"><h2>История</h2><small>Последние 7 дней</small></div><div class="history">${days.map(date=>{const record=store.record(date),count=store.completed(code,date),metrics=metricText(code,store.checkin(code,date));return `<button data-date="${date}"><span><b>${date===TODAY()?'Сегодня':formatDay(date)}</b><small>${record?`${count} из ${actions.length} действий`:'Нет данных'}</small></span><em>${metrics||'—'} ›</em></button>`}).join('')}</div><div class="section"><h2>Наблюдение</h2></div><section class="card insight"><p>${observation(code)}</p><small>Причинно-следственная связь не установлена</small></section><div class="section"><h2>Следующее улучшение</h2><small>Один эксперимент</small></div>${improvement()}<div class="section"><h2>Связи между стеками</h2><small>Личный паттерн</small></div><section class="card discipline relationship"><p class="eyebrow">${link.title}</p><p class="subtitle">${link.text}</p><i><span style="width:${link.progress}%"></span></i><small>Не медицинский вывод · минимум 5 совместных дней</small></section>`}

export function profileView(){const goal=STACK_LIBRARY[store.state.goal]||STACK_LIBRARY.SLEEP;return `${header('Профиль','Настройки системы и подключений.')}<section class="card profile"><p class="eyebrow">Стартовая цель</p><h2>${goal.title}</h2><p>${goal.code} STACK · ${store.state.moonConnected?'Moonvit подключён':'без Moonvit'}</p></section><div class="settings"><div><span>Активный стек</span><span>${store.state.activeStack} ›</span></div><div><span>Дней с действиями</span><span>${store.dataDays()} ›</span></div><button data-restart><span>Пройти настройку заново</span><span>›</span></button></div>`}

export function onboardingView(){const s=store.state,focus=s.goal==='FOCUS';const pages=[`<p class="eyebrow">Шаг 1 из 3</p><h1>Что ты хочешь улучшить?</h1><p class="subtitle">Начнём с одной цели. Остальные направления можно добавить позже.</p><div class="choices"><button class="${!focus?'selected':''}" data-goal="SLEEP"><b>Сон и восстановление</b><small>Режим, качество сна, энергия</small></button><button class="${focus?'selected':''}" data-goal="FOCUS"><b>Фокус и продуктивность</b><small>Концентрация и глубокая работа</small></button></div><button class="primary bottom" data-next>Продолжить</button>`,`<p class="eyebrow">Шаг 2 из 3</p><h1>Подключить Moonvit?</h1><p class="subtitle">Это необязательно. STACK остаётся системой дисциплины и без продукта.</p><div class="product-choice"><i></i><div><b>Moon</b><small>Sleep & Relaxation</small></div><span>${s.moonConnected?'Выбрано ✓':'Не подключён'}</span></div><button class="primary bottom" data-moon="yes">Подключить</button><button class="secondary" data-moon="no">Пока без Moonvit</button>`,`<p class="eyebrow">Шаг 3 из 3</p><h1>Твой ${s.goal} STACK готов</h1><p class="subtitle">Действия → дисциплина → состояние → наблюдения → улучшение.</p><div class="stack-list">${STACK_LIBRARY[s.goal].actions.filter(a=>s.moonConnected||!a.product).map(a=>`<span>${a.title}</span>`).join('')}</div><button class="primary bottom" data-finish>Начать</button>`];return `<div class="onboarding"><div class="dots">${pages.map((_,i)=>`<i class="${i===s.onboardingStep?'active':''}"></i>`).join('')}</div>${pages[s.onboardingStep]}</div>`}

export function modal(content){document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap"><div class="modal" role="dialog" aria-modal="true"><button class="close" data-close aria-label="Закрыть">×</button>${content}</div></div>`)}
export function checkinModal(code=store.state.activeStack){const stack=STACK_LIBRARY[code],saved=store.checkin(code)||{};modal(`<p class="eyebrow">${stack.checkin.eyebrow}</p><h2>${stack.checkin.title}</h2><div class="checkin-fields">${stack.checkin.questions.map(q=>`<label>${q.label} <output data-output="${q.key}">${saved[q.key]||3}</output></label><input data-metric="${q.key}" type="range" min="1" max="5" value="${saved[q.key]||3}">`).join('')}</div><button class="primary" data-save-checkin="${code}">Сохранить состояние</button>`)}
export function builderModal(){const choices=['FOCUS','TRAIN','BALANCE'].map(code=>STACK_LIBRARY[code]);modal(`<p class="eyebrow">Новое направление</p><h2>Что ты хочешь улучшить?</h2><p class="subtitle">Стек добавится в систему, но не перегрузит экран «Сегодня».</p><div class="presets">${choices.map((s,i)=>`<button class="${i===0?'selected':''}" data-preset="${s.code}"><strong>${s.icon}</strong><span><b>${s.title}</b><small>${store.state.installed.includes(s.code)?'Уже добавлен':`${s.actions.length} действия`}</small></span></button>`).join('')}</div><button class="primary" data-create="FOCUS">Добавить FOCUS STACK</button>`)}
export function dayModal(date){const code=store.state.activeStack,record=store.record(date),actions=store.actions(code),metrics=metricText(code,store.checkin(code,date));modal(`<p class="eyebrow">${formatDay(date)} · ${code} STACK</p><h2>${record?'Данные дня':'Пока нет данных'}</h2>${record?`<div class="day-detail">${actions.map(a=>`<span>${record.done.includes(a.id)?'✓':'○'} ${a.title}</span>`).join('')}</div><p class="subtitle">${metrics||'Состояние не оценено'}</p>`:'<p class="subtitle">В этот день отметки не сохранялись.</p>'}`)}
