import {STACK_LIBRARY,TODAY,formatDay,longToday} from './data.js';
import {store} from './store.js';

const header=(title,subtitle)=>`<header class="topbar"><div class="brand">STACK <span>× MOONVIT</span></div><div class="avatar">А</div></header><p class="eyebrow">${longToday()}</p><h1>${title}</h1><p class="subtitle">${subtitle}</p>`;
const task=a=>{const r=store.record(),done=r.done.includes(a.id);return `<button class="task ${done?'done':''}" data-task="${a.id}"><i>${done?'✓':''}</i><span><b>${a.title}</b><small>${a.checkin&&r.sleep?`Сон ${r.sleep}/5 · энергия ${r.energy}/5`:a.meta}</small></span>${a.product?'<em>Moonvit</em>':''}</button>`};
const observation=()=>{const rows=Object.values(store.state.records).filter(r=>r.sleep&&r.energy);if(rows.length<3)return `Нужно ещё ${3-rows.length} ежедневных отметки, чтобы STACK сформировал первое личное наблюдение.`;const avg=(rows.reduce((s,r)=>s+r.sleep,0)/rows.length).toFixed(1);return `За ${rows.length} отмеченных дня средняя субъективная оценка сна — ${avg} из 5. Данных пока недостаточно для вывода о причинах.`};

export function todayView(){const stack=store.stack(),actions=store.actions(),r=store.record(),done=r.done.filter(id=>actions.some(a=>a.id===id)).length;return `${header('Доброе утро, Алексей','Дисциплина начинается с нескольких ясных действий.')}<section class="hero"><div><h3>${stack.title}</h3><p>${stack.code==='SLEEP'&&store.state.moonConnected?'Эксперимент Moonvit · наблюдаем честно':'Активный план на сегодня'}</p></div><span>${stack.code} STACK</span><div class="progress"><i style="width:${actions.length?done/actions.length*100:0}%"></i></div>${stack.code==='SLEEP'&&store.state.moonConnected?'<div class="product"><i></i> Moon · Sleep & Relaxation</div>':''}</section><div class="section"><h2>Сегодня</h2><button data-reset>Сбросить</button></div><div class="tasks">${actions.map(task).join('')}</div><div class="section"><h2>STACK заметил</h2><button data-view="insights">История</button></div><section class="card insight"><p>${observation()}</p><small>Наблюдение, а не медицинский вывод</small></section>`}

export function stacksView(){return `${header('Твои стеки','Нажми на систему, чтобы сделать её активной.')}<div class="section"><h2>Мои системы</h2><small>${store.state.installed.length} всего</small></div><div class="stack-grid">${store.state.installed.map(code=>{const s=STACK_LIBRARY[code];return `<section class="stack-card ${store.state.activeStack===code?'active':''}" data-activate="${code}">${s.removable?`<button class="remove" data-remove="${code}" aria-label="Удалить ${code} STACK">×</button>`:''}<strong>${s.icon}</strong><small>${s.code} STACK</small><h2>${s.title}</h2><p>${store.actions(code).length} действия${code==='SLEEP'?` · ${store.state.moonConnected?'Moonvit подключён':'без Moonvit'}`:''}</p></section>`}).join('')}<button class="add-stack" data-builder>＋ Создать новый стек</button></div>`}

export function insightsView(){const actions=store.actions(),days=store.lastDays();return `${header('Прогресс','История без перегруженных графиков.')}<section class="card discipline"><p class="eyebrow">Дисциплина за 7 дней</p><div><b>${store.discipline()}%</b><span>выполненного плана</span></div><i><span style="width:${store.discipline()}%"></span></i></section><div class="section"><h2>История</h2><small>Последние 7 дней</small></div><div class="history">${days.map(d=>{const r=store.record(d),count=r?r.done.filter(id=>actions.some(a=>a.id===id)).length:0;return `<button data-date="${d}"><span><b>${d===TODAY()?'Сегодня':formatDay(d)}</b><small>${r?`${count} из ${actions.length} действий`:'Нет данных'}</small></span><em>${store.state.activeStack==='SLEEP'&&r?.sleep?`Сон ${r.sleep} · энергия ${r.energy}`:'—'} ›</em></button>`}).join('')}</div><div class="section"><h2>Наблюдение</h2></div><section class="card insight"><p>${observation()}</p><small>Причинно-следственная связь не установлена</small></section>`}

export function profileView(){return `${header('Профиль','Настройки твоей системы и подключений.')}<section class="card profile"><p class="eyebrow">Твоя цель</p><h2>${store.state.goal==='FOCUS'?'Улучшить фокус':'Улучшить сон'}</h2><p>${store.state.goal} STACK · ${store.state.moonConnected?'Moonvit Moon':'без Moonvit'}</p></section><div class="settings"><div><span>Moonvit</span><span>${store.state.moonConnected?'Подключён':'Не подключён'} ›</span></div><div><span>Дней с данными</span><span>${Object.keys(store.state.records).length} ›</span></div><button data-restart><span>Пройти настройку заново</span><span>›</span></button></div>`}

export function onboardingView(){const s=store.state,focus=s.goal==='FOCUS';const pages=[`<p class="eyebrow">Шаг 1 из 3</p><h1>Что ты хочешь улучшить?</h1><p class="subtitle">Начнём с одной цели. Остальное можно добавить позже.</p><div class="choices"><button class="${!focus?'selected':''}" data-goal="SLEEP"><b>Сон и восстановление</b><small>Режим, качество сна, энергия</small></button><button class="${focus?'selected':''}" data-goal="FOCUS"><b>Фокус и продуктивность</b><small>Концентрация и глубокая работа</small></button></div><button class="primary bottom" data-next>Продолжить</button>`,`<p class="eyebrow">Шаг 2 из 3</p><h1>Подключить Moonvit?</h1><p class="subtitle">Это необязательно. STACK останется полноценной системой без продукта.</p><div class="product-choice"><i></i><div><b>Moon</b><small>Sleep & Relaxation</small></div><span>${s.moonConnected?'Выбрано ✓':'Не подключён'}</span></div><button class="primary bottom" data-moon="yes">Подключить</button><button class="secondary" data-moon="no">Пока без Moonvit</button>`,`<p class="eyebrow">Шаг 3 из 3</p><h1>Твой ${s.goal} STACK готов</h1><p class="subtitle">Действия → дисциплина → состояние → наблюдения → улучшение.</p><div class="stack-list">${STACK_LIBRARY[s.goal].actions.filter(a=>s.moonConnected||!a.product).map(a=>`<span>${a.title}</span>`).join('')}</div><button class="primary bottom" data-finish>Начать</button>`];return `<div class="onboarding"><div class="dots">${pages.map((_,i)=>`<i class="${i===s.onboardingStep?'active':''}"></i>`).join('')}</div>${pages[s.onboardingStep]}</div>`}

export function modal(content){document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap"><div class="modal"><button class="close" data-close>×</button>${content}</div></div>`)}
export function checkinModal(){const r=store.record();modal(`<p class="eyebrow">Утренняя отметка</p><h2>Как ты себя чувствуешь?</h2><label>Качество сна <output id="sleepOut">${r.sleep||3}</output></label><input id="sleepRange" type="range" min="1" max="5" value="${r.sleep||3}"><label>Энергия <output id="energyOut">${r.energy||3}</output></label><input id="energyRange" type="range" min="1" max="5" value="${r.energy||3}"><button class="primary" data-save-checkin>Сохранить</button>`)}
export function builderModal(){const choices=['FOCUS','TRAIN','BALANCE'].map(code=>STACK_LIBRARY[code]);modal(`<p class="eyebrow">Новый стек</p><h2>Что ты хочешь улучшить?</h2><p class="subtitle">Выбери одно направление.</p><div class="presets">${choices.map((s,i)=>`<button class="${i===0?'selected':''}" data-preset="${s.code}"><strong>${s.icon}</strong><span><b>${s.title}</b><small>${s.code} STACK · ${s.actions.length} действия</small></span></button>`).join('')}</div><button class="primary" data-create="FOCUS">Создать FOCUS STACK</button>`)}
export function dayModal(date){const r=store.record(date),actions=store.actions();modal(`<p class="eyebrow">${formatDay(date)} · ${store.state.activeStack} STACK</p><h2>${r?'Данные дня':'Пока нет данных'}</h2>${r?`<div class="day-detail">${actions.map(a=>`<span>${r.done.includes(a.id)?'✓':'○'} ${a.title}</span>`).join('')}</div>${store.state.activeStack==='SLEEP'?`<p class="subtitle">Сон: ${r.sleep||'—'} из 5 · энергия: ${r.energy||'—'} из 5</p>`:''}`:'<p class="subtitle">В этот день отметки не сохранялись.</p>'}`)}
